name: PR Build Lint Check

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 26

      - name: Install dependencies
        run: npm install

      - name: Generate Drizzle
        run: npm run db:generate

      - name: Run lint
        env:
          CI: false
        run: npm run lint
